[package]
name = "cairo-types"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

serde.workspace = true

starknet.workspace = true

[features]
default = ["std"]
std = []
